tag-template: blueocean-display-url-$NEXT_PATCH_VERSION

replacers:
  - search: '/JENKINS-(\d+)/g'
    replace: '[JENKINS-$1](https://issues.jenkins-ci.org/browse/JENKINS-$1)'
exclude-lables:
  - internal
categories:
  - title: 🚀 Features
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
template: |
  ## What’s Changed

  $CHANGES
